version: '3.3'

services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    container_name: server
    build:
      context: ./pyke/server
      dockerfile: Dockerfile
    volumes:
      - './pyke/server:/usr/src/app'
    ports:
      - 3001:3000
    depends_on:
      - db
    links:
      - db

  client:
    container_name: client
    build:
      context: ./pyke/client
      dockerfile: Dockerfile
    volumes:
      - './pyke/client:/usr/src/app'
    ports:
      - '8081:8080'
    depends_on:
      - server
    links:
      - server
