version: '3.3'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src/app'
    environment:
      - SECRET_KEY=tempsecret
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
    ports:
      - '3007:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    links:
      - server
